// Drive the bare-metal link: our own linker script (flat image at 2 MiB),
// fully static, no dynamic linker. Relocation model is pinned to `static`
// in .cargo/config.toml so there is no GOT/PLT to relocate.
//
// Also embeds optional bitmap assets: any PNG present in `assets/` (see
// `ASSET_PROMPTS.md` for the expected files) is `include_bytes!`-embedded;
// anything absent compiles to `None`, so the kernel falls back to its
// procedural backdrop / 8×8 font and the build never breaks.

use std::env;
use std::fs;
use std::path::Path;

/// (generated constant name, filename the kernel looks for in `assets/`).
const ASSETS: &[(&str, &str)] = &[
    ("BG_LIST", "bg_list.png"),
    ("BG_BROWSER", "bg_browser.png"),
    ("BG_ROW", "bg_row.png"),
    ("BG_EDIT", "bg_edit.png"),
    ("BG_SCHEMA", "bg_schema.png"),
    ("BG_SHARED", "bg.png"),
    ("FONT", "font.png"),
];

fn main() {
    let dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    println!("cargo:rerun-if-changed=linker.ld");
    println!("cargo:rustc-link-arg=-T{dir}/linker.ld");
    println!("cargo:rustc-link-arg=-static");
    println!("cargo:rustc-link-arg=--no-dynamic-linker");

    let assets_dir = format!("{dir}/assets");
    println!("cargo:rerun-if-changed={assets_dir}");

    let mut gen = String::from(
        "// @generated by build.rs — optional embedded bitmap assets.\n\
         // `Some(..)` if the PNG exists in kernel/assets/, else `None`.\n",
    );
    for (name, file) in ASSETS {
        let path = format!("{assets_dir}/{file}");
        println!("cargo:rerun-if-changed={path}");
        if Path::new(&path).exists() {
            let fwd = path.replace('\\', "/");
            gen.push_str(&format!(
                "pub static {name}: Option<&[u8]> = Some(include_bytes!(\"{fwd}\"));\n"
            ));
        } else {
            gen.push_str(&format!("pub static {name}: Option<&[u8]> = None;\n"));
        }
    }

    let out = env::var("OUT_DIR").unwrap();
    fs::write(format!("{out}/assets_gen.rs"), gen).expect("write assets_gen.rs");
}
